import bcrypt from 'bcryptjs';

export default async () => [
  {
    name: 'Rockstar Games',
    email: 'rockstar@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Join a tight-knit team responsible for creating and publishing some of the most popular, innovative and critically acclaimed interactive entertainment in the world including the Grand Theft Auto series, the Red Dead series and many more. Known for our dedication to quality and authenticity, a career at Rockstar Games is an opportunity to work on some of the most cutting edge, creatively rewarding and challenging projects available in any entertainment medium with some of the most talented people in the industry. We offer successful candidates highly competitive salary and compensation packages, including a comprehensive benefits package for all eligible employees. Rockstar Games is an equal opportunity employer.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Rockstar_Games_Logo.svg/1200px-Rockstar_Games_Logo.svg.png',
    industry: 'Game Development',
    phone: '+1-555-0123',
    website: 'https://rockstargames.com',
    address: '123 Game Street',
    city: 'New York',
    country: 'USA',
    foundedYear: 1998,
    companySize: '1001-5000',
    socialMedia: {
      linkedin: 'rockstargames',
      twitter: 'rockstargames',
      facebook: 'rockstargames',
    },
    benefits: ['Health Insurance', 'Remote Work Options', '401(k) Match', 'Game Vouchers'],
    values: ['Quality', 'Authenticity', 'Innovation', 'Creativity'],
  },
  {
    name: 'UiPath',
    email: 'uipath@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `UiPath is a global software company that develops a platform for robotic process automation (RPA). The company's software monitors user activity to automate repetitive front and back office tasks, including those performed using other business software such as CRM or ERP systems. UiPath aims to democratize RPA and make automation accessible to everyone.`,
    avatar: 'https://upload.wikimedia.org/wikipedia/en/8/80/UiPath_2019_Corporate_Logo.png',
    industry: 'Software',
    phone: '+1-555-0102',
    website: 'https://uipath.com',
    address: '90 Park Avenue',
    city: 'New York',
    country: 'USA',
    foundedYear: 2005,
    companySize: '1001-5000',
    socialMedia: {
      linkedin: 'uipath',
      twitter: 'uipath',
      facebook: 'UiPath',
    },
    benefits: [
      'Stock Options',
      'Flexible Work Hours',
      'Health & Wellness Programs',
      'Learning & Development Budget',
    ],
    values: ['Humility', 'Boldness', 'Immersion', 'Fast'],
  },
  {
    name: 'eMAG',
    email: 'emag@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `eMAG is a Romanian e-commerce company, owned by Naspers. It sells a wide range of products, from electronics and IT products to books, toys, and fashion. eMAG is one of the largest online retailers in Central and Eastern Europe, operating in Romania, Bulgaria, Hungary, and Poland. The company focuses on providing a seamless online shopping experience.`,
    avatar: 'https://s13emagst.akamaized.net/layout/ro/images/logo//59/88362.svg',
    industry: 'E-commerce',
    phone: '+40-555-0103',
    website: 'https://emag.ro',
    address: 'Șoseaua Virtuții 148',
    city: 'Bucharest',
    country: 'ROU',
    foundedYear: 2001,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'emag.ro',
      twitter: 'emag',
      facebook: 'eMAG.ro',
    },
    benefits: [
      'Employee Discounts',
      'Medical Subscription',
      'Bookster Subscription',
      'Flexible Benefits Package',
    ],
    values: ['Customer Obsession', 'Innovation', 'Freedom to Create', 'Team Spirit'],
  },
  {
    name: 'Google',
    email: 'google@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five companies in the American information technology industry, alongside Amazon, Apple, Meta, and Microsoft.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png',
    industry: 'Information Technology',
    phone: '+1-555-0104',
    website: 'https://google.com',
    address: '1600 Amphitheatre Parkway',
    city: 'Mountain View',
    country: 'USA',
    foundedYear: 1998,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'google',
      twitter: 'google',
      facebook: 'Google',
    },
    benefits: [
      'On-site Meals & Snacks',
      'Comprehensive Health Plans',
      'Parental Leave',
      'Fitness Centers',
    ],
    values: [
      'Focus on the user and all else will follow',
      'It’s best to do one thing really, really well',
      'Fast is better than slow',
    ],
  },
  {
    name: 'Microsoft',
    email: 'microsoft@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services. Its best-known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/240px-Microsoft_logo.svg.png',
    industry: 'Software',
    phone: '+1-555-0105',
    website: 'https://microsoft.com',
    address: 'One Microsoft Way',
    city: 'Redmond',
    country: 'USA',
    foundedYear: 1975,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'microsoft',
      twitter: 'microsoft',
      facebook: 'Microsoft',
    },
    benefits: [
      'Health Insurance',
      'Retirement Plans',
      'Paid Time Off',
      'Employee Stock Purchase Plan',
    ],
    values: [
      'Innovation',
      'Diversity and inclusion',
      'Corporate social responsibility',
      'Trustworthy computing',
    ],
  },
  {
    name: 'Apple',
    email: 'apple@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Apple Inc. is an American multinational technology company that specializes in consumer electronics, software, and online services. Apple is the largest information technology company by revenue and, since January 2021, the world's most valuable company. It is considered one of the Big Five American information technology companies, alongside Amazon, Google, Microsoft, and Meta.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png',
    industry: 'Consumer Electronics',
    phone: '+1-555-0106',
    website: 'https://apple.com',
    address: 'One Apple Park Way',
    city: 'Cupertino',
    country: 'USA',
    foundedYear: 1976,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'apple',
      twitter: 'apple',
      facebook: 'apple',
    },
    benefits: [
      'Product Discounts',
      'Health and Wellness Programs',
      'Stock Grants',
      'Career Development',
    ],
    values: ['Innovation', 'Simplicity', 'Design', 'Accessibility'],
  },
  {
    name: 'Amazon',
    email: 'amazon@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Amazon.com, Inc. is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence. It has been referred to as "one of the most influential economic and cultural forces in the world", and is one of the world's most valuable brands.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1200px-Amazon_logo.svg.png',
    industry: 'E-commerce',
    phone: '+1-555-0107',
    website: 'https://amazon.com',
    address: '410 Terry Ave N',
    city: 'Seattle',
    country: 'USA',
    foundedYear: 1994,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'amazon',
      twitter: 'amazon',
      facebook: 'Amazon',
    },
    benefits: ['Comprehensive Healthcare', 'Paid Time Off', 'Employee Discount', 'Stock Options'],
    values: ['Customer Obsession', 'Ownership', 'Invent and Simplify', 'Learn and Be Curious'],
  },
  {
    name: 'Tesla',
    email: 'tesla@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Tesla, Inc. is an American electric vehicle and clean energy company based in Austin, Texas. Tesla designs and manufactures electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services. Tesla is one of the world's most valuable companies and remains the world's most valuable automaker.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/1200px-Tesla_Motors.svg.png',
    industry: 'Automotive',
    phone: '+1-555-0108',
    website: 'https://tesla.com',
    address: '13101 Harold Green Road',
    city: 'Austin',
    country: 'USA',
    foundedYear: 2003,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'tesla-motors',
      twitter: 'tesla',
      facebook: 'TeslaMotors',
    },
    benefits: ['Stock Options', 'Health Insurance', 'Employee Discounts on Products', 'Paid Leave'],
    values: ['Innovation', 'Sustainability', 'Safety', 'Excellence'],
  },
  {
    name: 'Netflix',
    email: 'netflix@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Netflix, Inc. is an American subscription streaming service and production company. Launched on August 29, 1997, it offers a library of films and television series through distribution deals as well as its own productions, known as Netflix Originals. Netflix is a pioneer in the streaming media space and one of the world's leading entertainment services.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1200px-Netflix_2015_logo.svg.png',
    industry: 'Entertainment',
    phone: '+1-555-0109',
    website: 'https://netflix.com',
    address: '100 Winchester Circle',
    city: 'Los Gatos',
    country: 'USA',
    foundedYear: 1997,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'netflix',
      twitter: 'netflix',
      facebook: 'netflix',
    },
    benefits: [
      'Unlimited Vacation Policy',
      'Health and Dental Plans',
      'Parental Leave',
      'Free Netflix Subscription',
    ],
    values: [
      'Judgment',
      'Communication',
      'Curiosity',
      'Courage',
      'Passion',
      'Selflessness',
      'Innovation',
      'Inclusion',
      'Integrity',
      'Impact',
    ],
  },
  {
    name: 'Spotify',
    email: 'spotify@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Spotify is a Swedish audio streaming and media services provider founded on 23 April 2006 by Daniel Ek and Martin Lorentzon. It is one of the largest music streaming service providers, with over 381 million monthly active users, including 172 million paying subscribers, as of September 2021. Spotify offers digital copyright restricted recorded music and podcasts, including more than 70 million songs, from record labels and media companies.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Spotify_App_Logo.svg/1200px-Spotify_App_Logo.svg.png',
    industry: 'Music Streaming',
    phone: '+46-555-0110',
    website: 'https://spotify.com',
    address: 'Regeringsgatan 19',
    city: 'Stockholm',
    country: 'SWE',
    foundedYear: 2006,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'spotify',
      twitter: 'spotify',
      facebook: 'Spotify',
    },
    benefits: [
      'Flexible Work Arrangements',
      'Parental Leave',
      'Wellness Allowance',
      'Learning Opportunities',
    ],
    values: ['Innovation', 'Collaboration', 'Passion', 'Transparency', 'Playfulness'],
  },
  {
    name: 'BMW Group',
    email: 'bmw@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Bayerische Motoren Werke AG, commonly referred to as BMW, is a German multinational corporate manufacturer of luxury vehicles and motorcycles headquartered in Munich, Bavaria, Germany. The corporation was founded in 1916 as a manufacturer of aircraft engines, which it produced from 1917 until 1918 and again from 1933 to 1945. Automobiles are marketed under the brands BMW, Mini and Rolls-Royce, and motorcycles are marketed under the brand BMW Motorrad.`,
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/1200px-BMW.svg.png',
    industry: 'Automotive',
    phone: '+49-555-0111',
    website: 'https://bmwgroup.com',
    address: 'Petuelring 130',
    city: 'Munich',
    country: 'DEU',
    foundedYear: 1916,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'bmw-group',
      twitter: 'bmwgroup',
      facebook: 'BMWGroup',
    },
    benefits: ['Company Car Options', 'Pension Scheme', 'Health Management', 'Employee Discounts'],
    values: ['Responsibility', 'Trust', 'Openness', 'Passion', 'Appreciation'],
  },
  {
    name: 'Lego Group',
    email: 'lego@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `The Lego Group is a Danish toy production company based in Billund. It is best known for the manufacture of Lego-brand toys, consisting mostly of interlocking plastic bricks. The Lego Group has also built several amusement parks around the world, each known as Legoland, and operates numerous retail stores. The company's motto is "Only the best is good enough" (Danish: Det bedste er ikke for godt).`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/LEGO_logo.svg/1200px-LEGO_logo.svg.png',
    industry: 'Toys',
    phone: '+45-555-0112',
    website: 'https://lego.com',
    address: 'Åstvej 1',
    city: 'Billund',
    country: 'DNK',
    foundedYear: 1932,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'the-lego-group',
      twitter: 'lego_group',
      facebook: 'LEGO',
    },
    benefits: [
      'Employee Discount on Products',
      'Playful Work Environment',
      'Development Opportunities',
      'Family Support Policies',
    ],
    values: ['Imagination', 'Creativity', 'Fun', 'Learning', 'Caring', 'Quality'],
  },
  {
    name: 'Samsung Electronics',
    email: 'samsung@example.com',
    password: bcrypt.hashSync('supersecretpassword'),
    role: 'company',
    active: true,
    confirmed: true,
    description: `Samsung Electronics Co., Ltd. is a South Korean multinational electronics corporation headquartered in Yeongtong-gu, Suwon, South Korea. It is the pinnacle of the Samsung chaebol, accounting for 70% of the group's revenue in 2012. Samsung Electronics has played a key role in the group's corporate governance due to circular ownership. Samsung Electronics is the world's largest manufacturer of mobile phones and smartphones.`,
    avatar:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/1200px-Samsung_Logo.svg.png',
    industry: 'Electronics',
    phone: '+82-555-0113',
    website: 'https://samsung.com',
    address: '129 Samsung-ro',
    city: 'Suwon',
    country: 'KOR',
    foundedYear: 1969,
    companySize: '5000+',
    socialMedia: {
      linkedin: 'samsung-electronics',
      twitter: 'samsung',
      facebook: 'Samsung',
    },
    benefits: [
      'Performance Incentives',
      'Global Mobility Programs',
      'Health & Wellness Support',
      'Training and Development',
    ],
    values: ['People', 'Excellence', 'Change', 'Integrity', 'Co-prosperity'],
  },
];
