import {
  EMPLOYMENT_TYPE,
  EXPERIENCE_LEVEL,
  MINIMUM_QUALIFICATION,
  WORKPLACE_TYPE,
} from 'constants/job'; // These are the constants you provided
import { addMonths, addYears } from 'date-fns';

export default async (companies) => {
  const rockstarGames = companies.find((c) => c.name === 'Rockstar Games');
  const uiPath = companies.find((c) => c.name === 'UiPath');
  const emag = companies.find((c) => c.name === 'eMAG');
  const google = companies.find((c) => c.name === 'Google');
  const microsoft = companies.find((c) => c.name === 'Microsoft');
  const tesla = companies.find((c) => c.name === 'Tesla');
  const spotify = companies.find((c) => c.name === 'Spotify');
  const apple = companies.find((c) => c.name === 'Apple');
  const amazon = companies.find((c) => c.name === 'Amazon');
  const bmwGroup = companies.find((c) => c.name === 'BMW Group');
  const legoGroup = companies.find((c) => c.name === 'Lego Group');

  return [
    {
      title: 'Senior Game Engine Developer (C++)',
      company: rockstarGames._id,
      description: `Join Rockstar Games to work on our next-generation game engine. We are seeking an experienced C++ developer to contribute to cutting-edge graphics, physics, or AI systems that power our critically acclaimed titles.
This is a full-time, permanent and in-office position based in Rockstar’s state-of-the-art game development studio in Edinburgh, Scotland.`,
      numberOfOpenings: 2,
      city: 'Edinburgh',
      country: 'GBR',
      workplaceType: WORKPLACE_TYPE.ONSITE,
      responsibilities: [
        'Design, develop, and maintain core game engine components in C++.',
        'Optimize engine performance for various gaming platforms (PC, Consoles).',
        'Collaborate with game teams to integrate engine features and provide support.',
        'Research and implement advanced rendering techniques, physics simulations, or AI algorithms.',
        'Write robust, maintainable, and highly performant code.',
      ],
      requiredSkills: [
        'C++',
        'Game Engine Architecture',
        '3D Math',
        'Performance Optimization',
        'Debugging Tools',
        'Multithreading',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 5000,
        max: 7500,
      },
      benefits: [
        'Comprehensive health insurance (medical, dental, vision)',
        'Generous pension scheme',
        'Paid time off and holidays',
        'Relocation assistance package',
        'Access to company game library and events',
        'Gym membership discount',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.SENIOR,
      deadlineDate: addYears(new Date(), 1),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: uiPath._id,
      title: 'Senior RPA Solutions Architect',
      description:
        'As a Senior RPA Solutions Architect at UiPath, you will lead the design of complex automation solutions for enterprise clients, leveraging the full capabilities of the UiPath platform. You will act as a technical expert and mentor.',
      numberOfOpenings: 5,
      city: 'New York',
      country: 'USA',
      workplaceType: WORKPLACE_TYPE.REMOTE,
      responsibilities: [
        'Lead the design and architecture of enterprise-scale RPA solutions.',
        'Provide technical guidance and best practices to clients and development teams.',
        'Conduct workshops to identify and analyze automation opportunities.',
        'Develop reusable components and frameworks for RPA projects.',
        'Mentor junior RPA developers and contribute to internal knowledge base.',
      ],
      requiredSkills: [
        'UiPath (Advanced Certified)',
        'RPA Solution Design',
        'Process Mining',
        'AI/ML Integration',
        'C# or VB.NET',
        'Cloud Platforms (Azure/AWS)',
        'Stakeholder Management',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 10833,
        max: 15000,
      },
      benefits: [
        'Competitive stock options',
        'Comprehensive health, dental, and vision plans',
        '401(k) with company match',
        'Unlimited PTO (based on policy)',
        'Professional development budget',
        'Home office stipend',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.SENIOR,
      deadlineDate: addYears(new Date(), 1),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: emag._id,
      title: 'Backend Developer (Java/Spring Boot)',
      description:
        'eMAG is looking for a passionate Backend Developer to join our Marketplace team. You will be responsible for developing and maintaining scalable microservices that power one of the largest e-commerce platforms in the region.',
      numberOfOpenings: 4,
      city: 'Bucharest',
      country: 'ROU',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Design, develop, and deploy robust and scalable backend services using Java and Spring Boot.',
        'Build and maintain APIs for internal and external consumers.',
        'Work with databases (SQL and NoSQL) to ensure data consistency and performance.',
        'Collaborate with frontend developers, QA engineers, and product owners in an Agile environment.',
        'Participate in architectural discussions and contribute to system design.',
      ],
      requiredSkills: [
        'Java',
        'Spring Boot',
        'Microservices',
        'REST APIs',
        'SQL (e.g., PostgreSQL)',
        'NoSQL (e.g., Cassandra, Redis)',
        'Docker',
        'Kubernetes',
        'Git',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 666,
        max: 1083,
      },
      benefits: [
        'Medical subscription at a private clinic',
        'Employee discounts on eMAG products',
        'Bookster library subscription',
        'Flexible benefits package (sports, travel, etc.)',
        'Annual performance bonus',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 9),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: google._id,
      title: 'AI Research Scientist - Natural Language Processing',
      description:
        'Google AI is seeking exceptional Research Scientists to push the boundaries of Natural Language Processing. You will work on fundamental research problems, develop novel models, and publish your findings in top-tier conferences.',
      numberOfOpenings: 7,
      city: 'Zurich',
      country: 'CHE',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Conduct cutting-edge research in NLP, including areas like large language models, machine translation, or conversational AI.',
        'Develop and implement novel algorithms and machine learning models.',
        'Publish research findings in leading academic venues (NeurIPS, ICML, ACL, etc.).',
        'Collaborate with other researchers and engineers on ambitious projects.',
        "Contribute to Google's AI products and services.",
      ],
      requiredSkills: [
        'Python',
        'TensorFlow or PyTorch or JAX',
        'Deep Learning',
        'Natural Language Processing (NLP)',
        'Machine Learning Theory',
        'Strong publication record',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.PHD,
      salary: {
        min: 12500,
        max: 20833,
      },
      benefits: [
        'World-class research environment',
        'Generous research budget and computational resources',
        'Highly competitive salary and stock options',
        'Comprehensive health and wellness programs',
        'Relocation assistance',
        'Opportunities for conference travel',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.SENIOR,
      deadlineDate: addYears(new Date(), 1),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: microsoft._id,
      title: 'UX Designer - Cloud & Enterprise',
      description:
        'Microsoft is looking for a talented UX Designer to create intuitive and engaging experiences for our Cloud & Enterprise products (e.g., Azure, Dynamics 365). You will work within a collaborative, multi-disciplinary team to shape the future of enterprise software.',
      numberOfOpenings: 5,
      city: 'Redmond',
      country: 'USA',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Design user flows, wireframes, prototypes, and high-fidelity mockups for complex enterprise applications.',
        'Conduct user research, usability testing, and gather feedback to inform design decisions.',
        'Collaborate closely with product managers, engineers, and researchers.',
        'Advocate for user-centered design principles and best practices.',
        'Contribute to and maintain design systems and style guides.',
      ],
      requiredSkills: [
        'UX Design',
        'UI Design',
        'Figma or Sketch or Adobe XD',
        'Prototyping',
        'User Research',
        'Usability Testing',
        'Interaction Design',
        'Design Systems',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 9166,
        max: 14166,
      },
      benefits: [
        'Comprehensive health benefits',
        'Employee stock purchase plan (ESPP)',
        '401(k) with company match',
        'Paid vacation and sick leave',
        'Parental leave',
        'Professional development resources',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 7),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: tesla._id,
      title: 'Firmware Engineer - Autopilot',
      description:
        "Join Tesla's Autopilot team to develop and deploy firmware for the world's most advanced driver-assistance systems. You will work on safety-critical software that is core to Tesla's mission of accelerating the world's transition to sustainable energy.",
      numberOfOpenings: 8,
      city: 'Palo Alto',
      country: 'USA',
      workplaceType: WORKPLACE_TYPE.ONSITE,
      responsibilities: [
        'Design, develop, and test firmware for embedded systems in Tesla vehicles.',
        'Work on low-level drivers, real-time operating systems (RTOS), and hardware bring-up.',
        'Optimize firmware for performance, power consumption, and reliability.',
        'Collaborate with hardware engineers and AI researchers on Autopilot features.',
        'Ensure compliance with safety standards (e.g., ISO 26262).',
      ],
      requiredSkills: [
        'C/C++',
        'Embedded Systems',
        'Firmware Development',
        'RTOS',
        'Microcontrollers (ARM, etc.)',
        'Debugging Tools (JTAG, Oscilloscopes)',
        'Linux Kernel (optional)',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 10000,
        max: 15833,
      },
      benefits: [
        'Tesla stock options',
        'Comprehensive medical, dental, vision coverage',
        'Employee discounts on Tesla products and services',
        'Relocation assistance',
        'Catered meals and snacks',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 10),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: spotify._id,
      title: 'Product Manager - Creator Tools',
      description:
        'Spotify is looking for an experienced Product Manager to lead the strategy and development of tools for music creators and podcasters. You will empower artists to connect with their fans and build their careers on our platform.',
      numberOfOpenings: 2,
      city: 'London',
      country: 'GBR',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Define and champion the product vision, strategy, and roadmap for creator-facing tools.',
        'Conduct market research, user interviews, and data analysis to identify creator needs.',
        'Prioritize features and write detailed product requirements and user stories.',
        'Collaborate with engineering, design, research, and marketing teams to deliver impactful products.',
        'Track product performance and iterate based on data and user feedback.',
      ],
      requiredSkills: [
        'Product Management',
        'Agile Methodologies',
        'User-Centric Design',
        'Data Analysis',
        'A/B Testing',
        'Technical Acumen',
        'Experience with creator economy or music industry is a plus',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 5833,
        max: 9166,
      },
      benefits: [
        'Flexible work arrangements and generous leave policies',
        'Parental leave support',
        'Wellness allowance and programs',
        'Stock options/RSUs',
        'Opportunities for international collaboration',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.SENIOR,
      deadlineDate: addYears(new Date(), 1),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: apple._id,
      title: 'Hardware Engineer - Silicon Validation',
      description:
        "Join Apple's silicon engineering group to be a part of the team that designs and validates the custom chips powering iPhone, iPad, Mac, and Apple Watch. This role focuses on post-silicon validation and characterization.",
      numberOfOpenings: 6,
      city: 'Cupertino',
      country: 'USA',
      workplaceType: WORKPLACE_TYPE.ONSITE,
      responsibilities: [
        'Develop and execute validation plans for complex SoCs and IP blocks.',
        'Bring up and debug new silicon in a lab environment.',
        'Design and implement test automation scripts (Python, Perl, etc.).',
        'Characterize performance, power, and functionality of silicon features.',
        'Collaborate with design, DFT, and software teams to resolve issues.',
      ],
      requiredSkills: [
        'Silicon Validation',
        'Post-Silicon Debug',
        'Lab Equipment (Oscilloscopes, Logic Analyzers)',
        'Scripting (Python, Perl)',
        'SoC Architecture',
        'Digital Design Fundamentals',
        'JTAG',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 6250,
        max: 9166,
      },
      benefits: [
        'Highly competitive salary and RSUs',
        'Employee stock purchase plan (ESPP)',
        'Comprehensive health and wellness benefits',
        'Product discounts',
        'On-site cafes and fitness centers',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 8),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: amazon._id,
      title: 'Cloud Support Engineer - AWS',
      description:
        'Amazon Web Services (AWS) is seeking Cloud Support Engineers to provide technical assistance to customers using our vast suite of cloud services. You will troubleshoot complex issues and help customers optimize their AWS environments.',
      numberOfOpenings: 20,
      city: 'Dublin',
      country: 'IRL',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Provide timely and effective technical support to AWS customers via phone, chat, and email.',
        'Troubleshoot issues related to various AWS services (EC2, S3, RDS, VPC, etc.).',
        'Assist customers with architectural design and best practices on AWS.',
        'Create and maintain technical documentation and knowledge base articles.',
        'Participate in on-call rotation for critical customer issues.',
      ],
      requiredSkills: [
        'AWS Services (EC2, S3, VPC, IAM, RDS, etc.)',
        'Linux or Windows System Administration',
        'Networking Concepts (TCP/IP, DNS)',
        'Troubleshooting',
        'Customer Service',
        'Scripting (Python, Bash, or PowerShell)',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 37500,
        max: 58333,
      },
      benefits: [
        'Amazon RSUs',
        'Comprehensive healthcare coverage',
        'Pension plan',
        'Paid time off',
        'Tuition reimbursement for further education',
        'Employee discounts',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addYears(new Date(), 1),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: bmwGroup._id,
      title: 'Autonomous Driving Software Engineer - Perception',
      description:
        'Join the BMW Group to develop cutting-edge software for autonomous driving systems. This role focuses on perception algorithms, using sensor data (camera, LiDAR, radar) to enable vehicles to understand their environment.',
      numberOfOpenings: 4,
      city: 'Munich',
      country: 'DEU',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Develop and implement perception algorithms for object detection, tracking, and scene understanding.',
        'Work with large-scale datasets from various sensors (camera, LiDAR, radar).',
        'Integrate software modules into the autonomous driving stack.',
        'Optimize algorithms for real-time performance on embedded automotive hardware.',
        'Contribute to system architecture and safety concepts (ISO 26262).',
      ],
      requiredSkills: [
        'C++',
        'Python',
        'Computer Vision',
        'Machine Learning (Deep Learning)',
        'Sensor Fusion',
        'Robotics (ROS is a plus)',
        'Software Development for Automotive',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.MASTER,
      salary: {
        min: 4583,
        max: 7083,
      },
      benefits: [
        'Competitive salary and performance bonuses',
        'Company car leasing options',
        'Comprehensive pension scheme',
        'Flexible working models',
        'On-site health services and canteen',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.SENIOR,
      deadlineDate: addMonths(new Date(), 9),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: legoGroup._id,
      title: 'Digital Play Designer - AR/VR Experiences',
      description:
        'The LEGO Group is looking for an innovative Digital Play Designer to create engaging augmented reality (AR) and virtual reality (VR) experiences that combine physical LEGO bricks with digital play. Bring your creativity to the future of play!',
      numberOfOpenings: 2,
      city: 'Billund',
      country: 'DNK',
      workplaceType: WORKPLACE_TYPE.ONSITE,
      responsibilities: [
        'Conceptualize and design interactive AR/VR play experiences for children.',
        'Prototype and iterate on game mechanics and user interfaces.',
        'Collaborate with software developers, 3D artists, and physical model designers.',
        'Conduct playtesting sessions and gather user feedback.',
        'Stay up-to-date with emerging technologies in AR/VR and digital play.',
      ],
      requiredSkills: [
        'Game Design',
        'AR/VR Development (Unity or Unreal Engine)',
        'User Experience (UX) Design for Children',
        'Prototyping Tools',
        '3D Modeling (basic understanding)',
        'Understanding of Child Development',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 37500,
        max: 58333,
      },
      benefits: [
        'Creative and playful work environment',
        'Employee discount on LEGO products',
        'Relocation assistance to Billund',
        'Comprehensive health and pension plans',
        'Opportunities for professional development',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 7),
      isActive: true,
      postedDate: new Date(),
    },
    {
      company: emag._id,
      title: 'Full Stack Developer (MERN Stack)',
      description:
        'eMAG is seeking a talented Full Stack Developer to join our innovative development team in Bucharest. You will work on building modern web applications using the MERN stack, contributing to our e-commerce platform that serves millions of customers across Eastern Europe.',
      numberOfOpenings: 3,
      city: 'Bucharest',
      country: 'ROU',
      workplaceType: WORKPLACE_TYPE.HYBRID,
      responsibilities: [
        'Develop and maintain scalable web applications using MongoDB, Express.js, React.js, and Node.js.',
        'Build responsive user interfaces and implement modern frontend features.',
        'Design and implement RESTful APIs and backend services.',
        'Collaborate with cross-functional teams in an Agile environment.',
        'Optimize application performance and ensure code quality through testing.',
        'Participate in code reviews and contribute to technical documentation.',
      ],
      requiredSkills: [
        'JavaScript',
        'React.js',
        'Node.js',
        'MongoDB',
        'Express.js',
        'REST APIs',
        'Git',
        'HTML/CSS',
        'SQL (PostgreSQL/MySQL)',
        'PHP (nice to have)',
      ],
      minimumQualification: MINIMUM_QUALIFICATION.BACHELOR,
      salary: {
        min: 750,
        max: 1250,
      },
      benefits: [
        'Medical subscription at a private clinic',
        'Employee discounts on eMAG products',
        'Flexible working hours and hybrid work model',
        'Professional development budget',
        'Annual performance bonus',
        'Modern office in central Bucharest',
      ],
      employmentType: EMPLOYMENT_TYPE.FULL_TIME,
      experienceLevel: EXPERIENCE_LEVEL.MID_LEVEL,
      deadlineDate: addMonths(new Date(), 6),
      isActive: true,
      postedDate: new Date(),
    },
  ];
};
